### ISSUE TITLE
detect for and do/while loops?

### ISSUE THREAD

**Issue by okayzed** [Gegel85/norminette#15]
http://paste.ubuntu.com/p/MRRyBND2mt/

 in https://github.com/Gegel85/norminette/blob/master/src/double_to_str.c there is a for loop as well as a do / while, but neither are flagged in the ouptut when running norminette on the codebase

**Comment by PinkySmile** [comment]
That is not forbidden so that's why it's not flagged

**Comment by okayzed** [comment]
in the PDFs i've seen in section II.8, it mentions they are forbidden. but i guess they are not, thanks!
