### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by RobertKoval** [Gegel85/norminette#2]
Roberts-iMac:norminette-master rkoval$ make
gcc -Iinclude  -W -Wall -Wextra    -c -o src/main.o src/main.c
src/main.c:12:10: fatal error: sys/sysmacros.h: No such file or directory
 #include <sys/sysmacros.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [src/main.o] Error 1
_____________
Mac OS X High Sierra

**Comment by PinkySmile** [comment]
Je suis désolé, mais pour l'instant il n'y a qu'une version Linux. Il n'y a pas les même fonctions et includes sur Mac et Windows.
