### ISSUE TITLE
trailling white space when using __attribute__

### ISSUE THREAD

**Issue by Cadichon** [Gegel85/norminette#6]
in this code:
```C
int trace_child(pid_t pid, __attribute__ ((unused)) const char *cmd)
{
	regs_t regs;
	int sig;

	while (waitpid(pid, &sig, 0) && !WIFEXITED(sig)) {
		if (ptrace(PTRACE_GETREGS, pid, NULL, &regs) == -1) {
			perror("ptrace(PTRACE_GETREGS, ...) failed\n");
			return (-1);
		}
		if (regs.orig_rax != ULLONG_MAX)
			printf("syscall\n");
		else
			printf("not a syscall\n");
		if (ptrace(PTRACE_SINGLESTEP, pid, NULL, NULL)) {
			perror("ptrace(PTRACE_SINGLESTEP, ...) failed\n");
			return (-1);
		}
	}
	return (0);
}
```
the norminette prompt a trailling white space in the first line at the end of `__attribute__`, but using attribute is norme friendly

**Comment by Leodau** [comment]
Indeed the norminette prompts out attributes as a trailing space, BUT , you should be better in terms of 'standars' using your "__attribute__ ((unused))" in a typedef style so you can just type something like. 

`#define UNUSED __attribute__((unused))`
`UNUSED const char *cmd`

No actual need to make an specific fix for this use.

**Comment by PinkySmile** [comment]
That should be fixed.
Thanks for reporting this :wink:
